# Generated by Django 3.2.7 on 2022-06-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='location',
            new_name='district',
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='position',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='finance',
            name='status',
            field=models.CharField(choices=[('employed', 'Employed'), ('not-employed', 'Not Employed')], default='employed', max_length=200),
        ),
        migrations.AlterField(
            model_name='finance',
            name='dependants',
            field=models.CharField(blank=True, choices=[('0', '0 Dependant'), ('1', '1 Dependant'), ('2', '2 Dependant'), ('3', '3 Dependant'), ('4', '4 Dependant'), ('5', '5 Dependant'), ('Above', 'Above 5')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='finance',
            name='duration',
            field=models.CharField(choices=[('Duration 1', 'Less Than 3 Months'), ('Duration 2', '3 Months-6 Months'), ('Duration 3', '6 Months-1 Year'), ('Duration 4', '1 Year-2 Years'), ('Duration 5', '2 Years-3 Years'), ('Duration 6', '3 Years-5 Years'), ('Duration 7', 'Above 5 Years')], default='Duration 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='finance',
            name='range',
            field=models.CharField(choices=[('Grade 1', 'Below 150,000'), ('Grade 2', '150,000-250,000'), ('Grade 3', '250,000-350,000'), ('Grade 4', '350,000-550,000'), ('Grade 5', '550,000-750,000'), ('Grade 6', '750,000-1,000,000'), ('Grade 7', 'Above 1,000,000')], default='Grade 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='finance',
            name='source',
            field=models.CharField(choices=[('consultant', 'Consultant'), ('business', 'Business'), ('freelance', 'Freelance')], default='employed', max_length=200),
        ),
    ]
