# Generated by Django 3.2.7 on 2022-05-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='employer',
            field=models.CharField(default='NIL', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='months',
            field=models.CharField(default='1 Month', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='nid',
            field=models.CharField(default='00000000000000', max_length=200),
        ),
    ]
