# Generated by Django 3.2.7 on 2022-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220505_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='office_phone',
            field=models.CharField(default='0712345743', max_length=200),
        ),
    ]
