# Generated by Django 3.2.7 on 2022-06-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220618_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='branch',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='finance',
            name='dependants',
            field=models.CharField(choices=[('0', '0 Dependant'), ('1', '1 Dependant'), ('2', '2 Dependant'), ('3', '3 Dependant'), ('4', '4 Dependant'), ('5', '5 Dependant'), ('Above', 'Above 5')], default='0', max_length=200),
        ),
    ]
