# Generated by Django 3.2.7 on 2022-06-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220623_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='referee',
            new_name='referee_number',
        ),
        migrations.AddField(
            model_name='finance',
            name='referee_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='finance',
            name='source',
            field=models.CharField(choices=[('employment', 'Employment'), ('consultant', 'Consultant'), ('business', 'Business'), ('freelance', 'Freelance')], default='employed', max_length=200),
        ),
    ]
