# Generated by Django 3.2.7 on 2022-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220618_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='means',
            field=models.CharField(choices=[('phone', 'Phone'), ('bank', 'Bank'), ('merchant', 'Merchant')], default='phone', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='number',
            field=models.CharField(default='00000000000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.CharField(default='0.000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lon',
            field=models.CharField(default='0.000000', max_length=200),
        ),
    ]
