# Generated by Django 3.2.7 on 2022-05-04 10:06

from django.db import migrations, models
import src.service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=src.service.models.upload_location),
        ),
    ]
