# Generated by Django 3.2.7 on 2022-06-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220618_1755'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='user',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='expected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.vendor'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
